using System;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem.UI;

namespace Sunward {
public sealed partial class FestivalHUD:MonoBehaviour {
 FestivalSession S;Canvas canvas;TMP_FontAsset font;Sprite panelSprite,ringSprite,dotSprite;Texture2D mapTexture;Vector2 mapMin,mapMax;
 RectTransform hud,menus,menuStage,miniMap,largeMap,miniPlayer,largePlayer,miniGate,largeGate;readonly List<GameObject> menuRoots=new();
 GameObject radioPanel;TextMeshProUGUI radioName,radioTitle,radioState,radioMenuStation,radioMenuTitle,radioMenuState,radioArtist,radioClock,radioPower,radioMute,masterLabel,musicLabel,effectsLabel;UnityEngine.UI.Image radioAccent,radioProgress,radioMenuProgress;UnityEngine.UI.Image[] stationCards;UnityEngine.UI.Slider masterSlider,musicSlider,effectsSlider;
 GameObject eventsPanel,garagePanel,mapPanel,pausePanel,resultPanel,welcome,noticeRoot,countdownRoot,driftRoot,raceRoot;CanvasGroup welcomeGroup,noticeGroup;
 TextMeshProUGUI speed,gear,credits,region,prompt,raceTitle,raceTimer,raceProgress,racePosition,countdown,countdownLabel,noticeTitle,noticeDetail,driftScore,driftMult,checkpointDistance;
 TextMeshProUGUI garageName,garageCategory,garageDescription,garageCredit,garageActionLabel,garagePaint,garageTune,resultTitle,resultTime,resultReward,resultDetails,exploredLabel;
 UnityEngine.UI.Image boostFill,speedArc,raceFill,menuBackdrop;UnityEngine.UI.Button garageAction,mapGarageButton;UnityEngine.UI.Image[] carCards,paintButtons,tuneButtons,statBars;
 readonly Color Ink=new(.047f,.071f,.098f,1),Panel=new(.055f,.08f,.105f,.94f),Cream=new(.96f,.94f,.87f),Muted=new(.58f,.66f,.67f),Yellow=new(1,.81f,.22f),Coral=new(1,.32f,.20f),Teal=new(.27f,.78f,.73f);
 float nextTextTick;bool initialized,ownsFont,lastLayoutRace;Vector2 lastCanvasSize;
 public void Initialize(FestivalSession session){S=session;font=TMP_Settings.defaultFontAsset;if(!font){font=TMP_FontAsset.CreateFontAsset(Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf"));font.name="Sunward Interface Sans";font.atlasPopulationMode=AtlasPopulationMode.Dynamic;ownsFont=true;}
  panelSprite=Shape(false,false);ringSprite=Shape(true,false);dotSprite=Shape(false,true);
  canvas=gameObject.AddComponent<Canvas>();canvas.renderMode=RenderMode.ScreenSpaceOverlay;canvas.sortingOrder=20;var scale=gameObject.AddComponent<UnityEngine.UI.CanvasScaler>();scale.uiScaleMode=UnityEngine.UI.CanvasScaler.ScaleMode.ScaleWithScreenSize;scale.referenceResolution=new Vector2(1920,1080);scale.matchWidthOrHeight=.5f;gameObject.AddComponent<UnityEngine.UI.GraphicRaycaster>();
  if(UnityEngine.Object.FindAnyObjectByType<EventSystem>()==null){var es=new GameObject("Festival Event System",typeof(EventSystem),typeof(InputSystemUIInputModule));es.transform.SetParent(transform,false);}
  hud=Fill(transform,"Driving HUD");menus=Fill(transform,"Menu Screens");menuBackdrop=Image(menus,new Color(Ink.r,Ink.g,Ink.b,.965f));menuBackdrop.raycastTarget=true;menuStage=Rect(menus,"Menu layout",0,0,1920,1080,.5f,.5f);menuStage.pivot=new Vector2(.5f,.5f);menuStage.anchoredPosition=Vector2.zero;BuildMapTexture();BuildDriving();BuildEvents();BuildGarage();BuildMap();BuildPause();BuildResults();BuildRadio();BuildPhoto();RefreshMenus();initialized=true;
 }
 RectTransform Rect(Transform parent,string name,float x,float y,float w,float h,float ax=0,float ay=1){var r=new GameObject(name,typeof(RectTransform)).GetComponent<RectTransform>();r.SetParent(parent,false);r.anchorMin=r.anchorMax=new Vector2(ax,ay);r.pivot=new Vector2(0,1);r.anchoredPosition=new Vector2(x,-y);r.sizeDelta=new Vector2(w,h);return r;}
 RectTransform Fill(Transform parent,string name){var r=new GameObject(name,typeof(RectTransform)).GetComponent<RectTransform>();r.SetParent(parent,false);r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=r.offsetMax=Vector2.zero;return r;}
 UnityEngine.UI.Image Image(RectTransform r,Color c,bool rounded=false){var image=r.gameObject.AddComponent<UnityEngine.UI.Image>();image.color=c;image.raycastTarget=false;if(rounded){image.sprite=panelSprite;image.type=UnityEngine.UI.Image.Type.Sliced;}return image;}
 UnityEngine.UI.Image Box(Transform p,string n,float x,float y,float w,float h,Color c,bool round=false,float ax=0,float ay=1)=>Image(Rect(p,n,x,y,w,h,ax,ay),c,round);
 TextMeshProUGUI Text(Transform p,string value,float x,float y,float w,float h,float size,Color c,FontStyles style=FontStyles.Normal,TextAlignmentOptions alignment=TextAlignmentOptions.TopLeft,float ax=0,float ay=1){var r=Rect(p,value.Length>30?value.Substring(0,30):value,x,y,w,h,ax,ay);var t=r.gameObject.AddComponent<TextMeshProUGUI>();t.font=font;t.text=value;t.fontSize=size;t.fontStyle=style;t.color=c;t.alignment=alignment;t.textWrappingMode=TextWrappingModes.NoWrap;t.overflowMode=TextOverflowModes.Ellipsis;t.raycastTarget=false;return t;}
 TextMeshProUGUI Label(Transform p,string s,float x,float y,float w=500,Color? color=null)=>Text(p,s,x,y,w,30,18,color??Muted,FontStyles.Bold);
 UnityEngine.UI.Button Button(Transform p,string label,float x,float y,float w,float h,Action action,bool accent=false){var image=Box(p,label,x,y,w,h,accent?Yellow:new Color(.13f,.18f,.20f,1),true);image.raycastTarget=true;var b=image.gameObject.AddComponent<UnityEngine.UI.Button>();b.targetGraphic=image;var colors=b.colors;colors.normalColor=Color.white;colors.highlightedColor=new Color(1.16f,1.16f,1.12f);colors.pressedColor=new Color(.70f,.72f,.67f);colors.selectedColor=Color.white;colors.disabledColor=new Color(.35f,.38f,.4f);b.colors=colors;b.onClick.AddListener(()=>action());Text(image.transform,label,18,0,w-36,h,21,accent?Ink:Cream,FontStyles.Bold,TextAlignmentOptions.MidlineLeft);return b;}
 void Rule(Transform p,float x,float y,float w,Color? c=null)=>Box(p,"Rule",x,y,w,2,c??new Color(.2f,.28f,.29f,.65f));
 GameObject Screen(string title,string eyebrow,bool dim=true){var root=Fill(menuStage,title);if(dim)Image(root,new Color(Ink.r,Ink.g,Ink.b,.965f)).raycastTarget=true;Label(root,eyebrow,64,44,1250,Yellow);Text(root,title,60,87,1780,100,64,Cream,FontStyles.Bold);Button(root,"CLOSE  /  ESC",-280,50,216,52,()=>S.CloseMenu()).GetComponent<RectTransform>().anchorMin=new Vector2(1,1);var close=root.GetChild(root.childCount-1).GetComponent<RectTransform>();close.anchorMax=new Vector2(1,1);menuRoots.Add(root.gameObject);return root.gameObject;}
 void BuildDriving(){
  Box(hud,"Festival identity plate",32,23,450,138,new Color(Ink.r,Ink.g,Ink.b,.78f),true);Label(hud,"THE OPEN ROAD IS YOURS",50,36,400,Yellow);Text(hud,"SUNWARD",46,63,415,62,51,Cream,FontStyles.Bold);Text(hud,"MOTOR FESTIVAL  /  COAST EDITION",50,126,415,28,19,Cream,FontStyles.Bold);
  var creditBox=Box(hud,"Collection balance",-310,42,260,70,Panel,true,1,1);Label(creditBox.transform,"FESTIVAL CREDITS",22,12,225);credits=Text(creditBox.transform,"1,600 CR",22,31,216,35,27,Cream,FontStyles.Bold,TextAlignmentOptions.TopRight);
  raceRoot=Box(hud,"Race telemetry",-366,35,732,120,Panel,true,.5f,1).gameObject;raceTitle=Label(raceRoot.transform,"COAST CIRCUIT",25,14,495,Yellow);raceTimer=Text(raceRoot.transform,"00:00.00",24,48,230,52,40,Cream,FontStyles.Bold);raceProgress=Text(raceRoot.transform,"CHECKPOINT 01 / 16",260,49,280,42,22,Cream,FontStyles.Bold);racePosition=Text(raceRoot.transform,"4 / 4",550,44,154,50,35,Cream,FontStyles.Bold,TextAlignmentOptions.TopRight);Box(raceRoot.transform,"Progress track",24,105,684,4,new Color(.23f,.29f,.29f));raceFill=Box(raceRoot.transform,"Progress",24,105,0,4,Yellow);
  var mapShell=Box(hud,"Island navigator",48,-328,264,264,Panel,true,0,0);miniMap=Rect(mapShell.transform,"Coast map",8,8,248,248);var raw=miniMap.gameObject.AddComponent<UnityEngine.UI.RawImage>();raw.texture=mapTexture;raw.color=Color.white;raw.raycastTarget=false;DrawLandmarks(miniMap,248,7);miniGate=Marker(miniMap,16,Yellow,false);miniPlayer=Marker(miniMap,16,Cream,true);Label(mapShell.transform,"N",224,10,24,Cream);region=Label(hud,"SUNWARD COAST",48,-53,550,Cream);region.rectTransform.anchorMin=region.rectTransform.anchorMax=new Vector2(0,0);
  var speedRoot=Rect(hud,"Speed instrument",-340,-323,290,270,1,0);var back=Box(speedRoot,"Dial background",12,2,256,256,new Color(Ink.r,Ink.g,Ink.b,.72f));back.sprite=dotSprite;var arcBack=Box(speedRoot,"Dial track",12,2,256,256,new Color(.24f,.30f,.29f,.65f));arcBack.sprite=ringSprite;speedArc=Box(speedRoot,"Speed arc",12,2,256,256,Yellow);speedArc.sprite=ringSprite;speedArc.type=UnityEngine.UI.Image.Type.Filled;speedArc.fillMethod=UnityEngine.UI.Image.FillMethod.Radial360;speedArc.fillOrigin=0;speedArc.fillClockwise=true;speedArc.fillAmount=.15f;
  speed=Text(speedRoot,"000",12,55,256,116,98,Cream,FontStyles.Bold,TextAlignmentOptions.Center);Text(speedRoot,"KM/H",70,177,140,30,20,Cream,FontStyles.Bold,TextAlignmentOptions.Center);gear=Text(speedRoot,"N",219,180,48,44,26,Yellow,FontStyles.Bold,TextAlignmentOptions.Center);Label(speedRoot,"BOOST  /  SHIFT",22,263,245,Cream);Box(speedRoot,"Boost track",20,294,250,8,new Color(.24f,.30f,.29f));boostFill=Box(speedRoot,"Boost",20,294,250,8,Teal);
  prompt=Text(hud,"WASD  DRIVE     SPACE  DRIFT     SHIFT  BOOST",-570,-40,1140,28,18,Cream,FontStyles.Bold,TextAlignmentOptions.Center,.5f,0);
  checkpointDistance=Text(hud,"",-310,170,620,40,22,Yellow,FontStyles.Bold,TextAlignmentOptions.Center,.5f,1);
  welcome=Box(hud,"Welcome to Sunward",-300,197,600,139,Panel,true,.5f,1).gameObject;welcomeGroup=welcome.AddComponent<CanvasGroup>();Label(welcome.transform,"WELCOME TO THE SUNWARD COAST",24,17,548,Yellow);Text(welcome.transform,"Take the long way.",23,43,550,46,33,Cream,FontStyles.Bold);Text(welcome.transform,"WASD drive   /   SPACE drift   /   SHIFT boost",24,94,552,28,21,Muted);
  noticeRoot=Box(hud,"Festival notification",-330,204,660,110,Panel,true,.5f,1).gameObject;noticeGroup=noticeRoot.AddComponent<CanvasGroup>();Box(noticeRoot.transform,"Accent",0,16,5,77,Yellow);noticeTitle=Text(noticeRoot.transform,"",25,19,612,39,27,Cream,FontStyles.Bold);noticeDetail=Text(noticeRoot.transform,"",25,66,612,30,19,Muted);
  countdownRoot=Rect(hud,"Start countdown",-250,-200,500,320,.5f,.5f).gameObject;countdown=Text(countdownRoot.transform,"3",0,0,500,212,168,Yellow,FontStyles.Bold,TextAlignmentOptions.Center);countdownLabel=Text(countdownRoot.transform,"FIND YOUR FLOW",0,210,500,50,26,Cream,FontStyles.Bold,TextAlignmentOptions.Center);
  driftRoot=Rect(hud,"Drift chain",-265,-28,530,112,.5f,.5f).gameObject;driftScore=Text(driftRoot.transform,"1,200",0,0,390,68,55,Yellow,FontStyles.Bold,TextAlignmentOptions.TopRight);driftMult=Text(driftRoot.transform,"x1",412,11,100,56,37,Cream,FontStyles.Bold);Text(driftRoot.transform,"STYLE CHAIN",180,75,260,32,18,Muted,FontStyles.Bold,TextAlignmentOptions.Center);
 }
 void BuildEvents(){eventsPanel=Screen("CHASE THE HORIZON.","SUNWARD / FESTIVAL EVENT BOARD");var p=eventsPanel.transform;Text(p,"Three roads. Four drivers. Your name on the clock.",64,184,1500,46,25,Muted);
  for(int i=0;i<S.Game.World.Roads.Count;i++){int index=i;var road=S.Game.World.Roads[i];float x=64+i*596;var card=Box(p,"Event "+i,x,281,562,570,Panel,true);var col=i==0?Yellow:i==1?Teal:Coral;Box(card.transform,"Route accent",0,0,562,8,col);Label(card.transform,"0"+(i+1)+"   /   CIRCUIT",28,31,470,col);Text(card.transform,road.Name.ToUpperInvariant(),28,77,510,102,38,Cream,FontStyles.Bold).textWrappingMode=TextWrappingModes.Normal;MiniRoute(card.transform,road,29,191,500,137,col);Label(card.transform,(road.Length/1000).ToString("0.0")+" KM   /   1 LAP   /   4 DRIVERS",28,355,500,Cream);Text(card.transform,"GOLD TARGET   "+FestivalSession.Clock(S.GoldTime(i)),28,401,500,34,20,Muted);Button(card.transform,"TAKE THE GRID",28,477,506,62,()=>S.StartEvent(index),true);}
  Text(p,"All events include timing, ordered checkpoints and rivals. Finish to earn credits and unlock your next car.",64,905,1670,44,23,Muted);Button(p,"EXPLORE THE MAP",64,979,300,54,()=>S.ShowMenu(FestivalMenu.Map));
 }
 void BuildGarage(){garagePanel=Screen("MAKE IT YOURS.","SUNWARD / THE ATELIER",false);var p=garagePanel.transform;var veil=Box(p,"Garage shade",0,0,676,1080,new Color(Ink.r,Ink.g,Ink.b,.97f));veil.transform.SetAsFirstSibling();garageCredit=Text(p,"",64,189,544,38,25,Yellow,FontStyles.Bold);carCards=new UnityEngine.UI.Image[CarSpec.All.Length];
  for(int i=0;i<CarSpec.All.Length;i++){int index=i;float x=64+i%2*281,y=257+i/2*114;var b=Button(p,"",x,y,260,96,()=>S.Preview(index));carCards[i]=b.GetComponent<UnityEngine.UI.Image>();Label(b.transform,"0"+(i+1)+" / "+CarSpec.All[i].Category,17,15,232);Text(b.transform,CarSpec.All[i].Name,17,44,230,37,25,Cream,FontStyles.Bold);}
  garageCategory=Label(p,"SPORT COUPE",64,512,530,Yellow);garageName=Text(p,"SEREIN 01",61,548,550,72,52,Cream,FontStyles.Bold);garageDescription=Text(p,"",64,630,530,80,23,Muted);garageDescription.textWrappingMode=TextWrappingModes.Normal;
  garagePaint=Label(p,"FINISH / EMBER",64,736,530,Cream);paintButtons=new UnityEngine.UI.Image[FestivalSession.Paints.Length];for(int i=0;i<paintButtons.Length;i++){int index=i;var b=Button(p,"",64+i*88,780,72,42,()=>S.Paint(index));paintButtons[i]=b.GetComponent<UnityEngine.UI.Image>();paintButtons[i].color=FestivalSession.Paints[i];}
  garageTune=Label(p,"TUNE / STREET",64,849,530,Cream);tuneButtons=new UnityEngine.UI.Image[3];for(int i=0;i<3;i++){int tune=i-1;var b=Button(p,FestivalSession.TuneNames[i],64+i*184,891,169,46,()=>S.Tune(tune));tuneButtons[i]=b.GetComponent<UnityEngine.UI.Image>();}
  garageAction=Button(p,"DRIVE THIS CAR",64,976,532,65,()=>S.DrivePreview(),true);garageActionLabel=garageAction.GetComponentInChildren<TextMeshProUGUI>();
  var stats=Box(p,"Vehicle character",737,819,1114,209,Panel,true);Label(stats.transform,"ENGINEERED FOR THE FEELING",28,22,930,Yellow);string[] labels={"VELOCITY","PUNCH","CORNERING"};statBars=new UnityEngine.UI.Image[3];for(int i=0;i<3;i++){float x=28+i*365;Label(stats.transform,labels[i],x,80,322,Cream);Box(stats.transform,"Stat track",x,130,318,8,new Color(.22f,.29f,.3f));statBars[i]=Box(stats.transform,"Stat",x,130,200,8,Yellow);}Text(stats.transform,"Each car and tune changes how you carry speed, rotate and recover.",28,166,1065,25,19,Muted);
 }
 void BuildMap(){mapPanel=Screen("A COAST WORTH GETTING LOST IN.","SUNWARD / DISCOVERY ATLAS");var p=mapPanel.transform;largeMap=Rect(p,"Discovery map",64,230,740,740);var raw=largeMap.gameObject.AddComponent<UnityEngine.UI.RawImage>();raw.texture=mapTexture;raw.raycastTarget=false;DrawLandmarks(largeMap,740,9);largeGate=Marker(largeMap,26,Yellow,false);largePlayer=Marker(largeMap,26,Cream,true);Label(largeMap,"NORTH",657,18,75,Cream);Label(p,"FIND YOUR NEXT STORY",867,231,910,Yellow);
  for(int i=0;i<S.Game.World.Roads.Count;i++){int index=i;var road=S.Game.World.Roads[i];float y=290+i*153;var b=Button(p,"",862,y,985,129,()=>S.StartEvent(index));Text(b.transform,"0"+(i+1),24,24,92,74,52,Yellow,FontStyles.Bold);Text(b.transform,road.Name.ToUpperInvariant(),131,24,690,42,31,Cream,FontStyles.Bold);Text(b.transform,(road.Length/1000).ToString("0.0")+" KM  /  CIRCUIT  /  ENTER EVENT",133,76,760,28,20,Muted);}
  exploredLabel=Text(p,"",866,784,880,45,25,Cream,FontStyles.Bold);Text(p,"Gold gate: next checkpoint   /   White arrow: your car\nColored dots: scenic discoveries. Get close to earn credits.",866,843,970,86,23,Muted).textWrappingMode=TextWrappingModes.Normal;Button(p,"RETURN TO FESTIVAL",865,965,406,65,()=>S.ReturnToFestival(),true);mapGarageButton=Button(p,"OPEN THE ATELIER",1294,965,550,65,()=>S.ShowMenu(FestivalMenu.Garage));
 }
 void BuildPause(){pausePanel=Screen("TAKE A BREATH.","SUNWARD / PAUSED");var p=pausePanel.transform;Text(p,"The coast will wait.",64,198,1000,52,29,Muted);Button(p,"BACK TO THE ROAD",64,327,600,72,()=>S.CloseMenu(),true);Button(p,"FESTIVAL EVENTS",64,423,600,72,()=>S.ShowMenu(FestivalMenu.Events));Button(p,"WORLD MAP",64,519,600,72,()=>S.ShowMenu(FestivalMenu.Map));Button(p,"RETURN TO FESTIVAL",64,615,600,72,()=>S.ReturnToFestival());Button(p,"ABANDON CURRENT EVENT",64,711,600,72,()=>S.AbandonEvent());Button(p,"QUIT GAME",64,807,600,72,QuitGame);Button(p,"RADIO & AUDIO  /  B",64,903,600,65,()=>S.ShowMenu(FestivalMenu.Radio));
  Button(p,"PHOTO MODE  /  P",64,244,600,60,()=>S.Game.Photo.Enter());
  var guide=Box(p,"Driver handbook",851,282,990,650,Panel,true);Label(guide.transform,"A FEW THINGS TO FEEL",35,35,920,Yellow);string[] keys={"W A S D / ARROWS","SPACE","LEFT SHIFT","R","C","E / G / M","BACKSPACE","F8","ESC"};string[] labels={"Throttle, brake / reverse, steer","Handbrake + drift","Hold for boost. Refills as you drive.","Return to your previous safe position","Change cinematic camera","Events / garage / discovery atlas","Race checkpoint recovery (+7 seconds)","Mute / unmute all audio","Pause / close menu"};for(int i=0;i<keys.Length;i++){float y=105+i*62;Text(guide.transform,keys[i],35,y,350,36,22,Cream,FontStyles.Bold);Text(guide.transform,labels[i],381,y,568,36,22,Muted);}Text(p,"Progress saves automatically: credits, owned cars, selected finish, tunes, discoveries and personal bests.",64,993,1760,39,22,Muted);
 }
 void QuitGame(){PlayerPrefs.Save();Time.timeScale=1;
#if UNITY_EDITOR
  UnityEditor.EditorApplication.isPlaying=false;
#else
  Application.Quit();
#endif
 }
 void BuildResults(){resultPanel=Screen("THAT WAS A DRIVE.","SUNWARD / FINISH LINE");var p=resultPanel.transform;var hero=Box(p,"Result medal",64,270,660,582,Panel,true);Label(hero.transform,"YOUR MOMENT",32,29,590,Yellow);resultTitle=Text(hero.transform,"GOLD",28,115,605,137,101,Yellow,FontStyles.Bold);resultTime=Text(hero.transform,"00:00.00",31,304,595,91,67,Cream,FontStyles.Bold);resultDetails=Text(hero.transform,"",33,441,590,93,25,Muted);resultDetails.textWrappingMode=TextWrappingModes.Normal;Label(p,"THE ROAD GIVES BACK",814,297,1000,Yellow);resultReward=Text(p,"+3,500 CR",808,365,1000,119,82,Cream,FontStyles.Bold);Text(p,"Another car. Another color. Another reason to go again.",814,521,990,80,30,Muted).textWrappingMode=TextWrappingModes.Normal;Button(p,"BACK TO FREE ROAM",814,673,996,79,()=>S.CloseMenu(),true);Button(p,"RUN IT AGAIN",814,783,478,67,()=>S.StartEvent(S.EventIndex));Button(p,"FESTIVAL EVENTS",1318,783,492,67,()=>S.ShowMenu(FestivalMenu.Events));
 }
 public void RefreshMenus(){if(hud==null)return;bool open=S.Menu!=FestivalMenu.None;hud.gameObject.SetActive(!open);menus.gameObject.SetActive(open);menuBackdrop.raycastTarget=S.Menu!=FestivalMenu.Photo;menuBackdrop.color=S.Menu==FestivalMenu.Garage||S.Menu==FestivalMenu.Photo?Color.clear:new Color(Ink.r,Ink.g,Ink.b,.965f);foreach(var root in menuRoots)root.SetActive(false);GameObject active=S.Menu switch{FestivalMenu.Events=>eventsPanel,FestivalMenu.Garage=>garagePanel,FestivalMenu.Map=>mapPanel,FestivalMenu.Pause=>pausePanel,FestivalMenu.Results=>resultPanel,FestivalMenu.Radio=>radioPanel,FestivalMenu.Photo=>photoPanel,_=>null};if(active)active.SetActive(true);RefreshPhoto();if(S.Menu==FestivalMenu.Garage)RefreshGarage();if(S.Menu==FestivalMenu.Results){resultTitle.text=S.ResultMedal;resultTime.text=FestivalSession.Clock(S.RaceTime);resultReward.text="+"+S.ResultReward.ToString("N0")+" CR";resultDetails.text="POSITION "+S.RacePlace+" / 4\n"+(S.PersonalBest?"NEW PERSONAL BEST":"BEST  "+FestivalSession.Clock(S.BestTime(S.EventIndex)));}if(mapGarageButton)mapGarageButton.interactable=S.State==FestivalRace.Cruise;if(exploredLabel)exploredLabel.text="DISCOVERED "+S.Discoveries+" / "+S.TotalDiscoveries+"  /  "+S.Credits.ToString("N0")+" CR";}
 public void RefreshGarage(){if(!garageName)return;var car=CarSpec.All[S.PreviewCar];garageName.text=car.Name;garageCategory.text=car.Category+(S.Owned(S.PreviewCar)?"  /  IN YOUR COLLECTION":"  /  AVAILABLE TO UNLOCK");garageDescription.text=car.Description;garageCredit.text=S.Credits.ToString("N0")+" CR  /  FESTIVAL BALANCE";garagePaint.text="FINISH / "+FestivalSession.PaintNames[S.PreviewPaint];garageTune.text="TUNE / "+FestivalSession.TuneNames[S.PreviewTune+1];garageActionLabel.text=S.Owned(S.PreviewCar)?"SAVE & DRIVE":"UNLOCK & DRIVE  /  "+car.Price.ToString("N0")+" CR";garageAction.interactable=S.Owned(S.PreviewCar)||S.Credits>=car.Price;for(int i=0;i<carCards.Length;i++)carCards[i].color=i==S.PreviewCar?new Color(.27f,.32f,.24f):new Color(.12f,.17f,.20f);for(int i=0;i<paintButtons.Length;i++){paintButtons[i].rectTransform.localScale=Vector3.one*(i==S.PreviewPaint?1.13f:1);paintButtons[i].color=FestivalSession.Paints[i];}for(int i=0;i<tuneButtons.Length;i++)tuneButtons[i].color=i==S.PreviewTune+1?new Color(.38f,.34f,.17f):new Color(.13f,.18f,.20f);statBars[0].rectTransform.sizeDelta=new Vector2(318*Mathf.Clamp01((car.TopSpeed+S.PreviewTune*10)/330),8);statBars[1].rectTransform.sizeDelta=new Vector2(318*Mathf.Clamp01((car.Power+S.PreviewTune*1.2f)/42),8);statBars[2].rectTransform.sizeDelta=new Vector2(318*Mathf.Clamp01((car.Grip-S.PreviewTune*.8f)/13),8);}
 void Update(){if(!initialized)return;Reflow();RefreshPhoto();if(S.Game.Photo.Active)return;var car=S.Game.Player;bool racing=S.State==FestivalRace.Racing||S.State==FestivalRace.Countdown;raceRoot.SetActive(racing);countdownRoot.SetActive(S.State==FestivalRace.Countdown);driftRoot.SetActive(S.DriftChain>40&&S.State!=FestivalRace.Countdown);speedArc.fillAmount=Mathf.Clamp01(car.SpeedKph/car.Spec.TopSpeed)*.79f+.06f;boostFill.rectTransform.sizeDelta=new Vector2(250*car.Boost01,8);raceFill.rectTransform.sizeDelta=new Vector2(684*(racing?S.RaceDistance/S.ActiveRoute.Length:0),4);
  PlaceMarker(miniPlayer,car.transform.position,248,true);PlaceMarker(largePlayer,car.transform.position,740,true);miniGate.gameObject.SetActive(racing);largeGate.gameObject.SetActive(racing);if(racing){PlaceMarker(miniGate,S.NextCheckpoint,248,false);PlaceMarker(largeGate,S.NextCheckpoint,740,false);}
  float now=Time.unscaledTime;noticeGroup.alpha=Mathf.Clamp01((S.NoticeUntil-now)*2);noticeRoot.SetActive(now<S.NoticeUntil&&S.State!=FestivalRace.Countdown);welcomeGroup.alpha=Mathf.Clamp01((S.WelcomeUntil-now)*1.4f);welcome.SetActive(now<S.WelcomeUntil&&now>=S.NoticeUntil&&S.State==FestivalRace.Cruise);
  if(now<nextTextTick)return;nextTextTick=now+.07f;RefreshRadio();speed.text=Mathf.RoundToInt(car.SpeedKph).ToString("000");gear.text=car.SpeedKph<3?"N":Mathf.Clamp(1+Mathf.FloorToInt(car.SpeedKph/48),1,6).ToString();credits.text=S.Credits.ToString("N0")+" CR";region.text=S.Region;prompt.text=S.ContextHint;noticeTitle.text=S.Notice;noticeDetail.text=S.NoticeDetail;driftScore.text=Mathf.RoundToInt(S.DriftChain).ToString("N0");driftMult.text="x"+S.ChainMultiplier;countdown.text=Mathf.Max(1,Mathf.CeilToInt(S.Countdown)).ToString();countdownLabel.text="FIND YOUR FLOW";
  if(racing){raceTitle.text=S.ActiveRoute.Name.ToUpperInvariant()+"  /  CIRCUIT";raceTimer.text=FestivalSession.Clock(S.RaceTime);raceProgress.text="GATE "+Mathf.Min(S.GateIndex+1,S.GateCount).ToString("00")+" / "+S.GateCount.ToString("00");racePosition.text=S.RacePlace+" / 4";checkpointDistance.text=S.State==FestivalRace.Racing?(S.MissedGate?"MISSED CHECKPOINT  /  BACKSPACE TO RECOVER":S.WrongWay?"WRONG WAY":Mathf.RoundToInt(Vector3.Distance(car.transform.position,S.NextCheckpoint))+" M  /  NEXT GATE"):"";}else checkpointDistance.text="";
 }
 void BuildRadio(){
  var r=S.Game.Radio;
  var card=Box(hud,"Radio now playing",-264,-173,528,112,Panel,true,.5f,0);radioAccent=Box(card.transform,"Station color",0,16,4,78,Teal);radioName=Text(card.transform,"TIDEGLASS  /  88.4",19,12,352,25,17,Teal,FontStyles.Bold);radioState=Text(card.transform,"NOW PLAYING",354,14,155,22,13,Muted,FontStyles.Bold,TextAlignmentOptions.TopRight);radioTitle=Text(card.transform,"Tuning in...",18,38,489,36,26,Cream,FontStyles.Bold);Box(card.transform,"Track timeline",19,79,490,2,new Color(.24f,.30f,.29f));radioProgress=Box(card.transform,"Track progress",19,79,0,2,Teal);Text(card.transform,"T STATION   N NEXT   B RADIO   P PHOTO",19,90,490,22,14,Muted,FontStyles.Bold);
  radioPanel=Screen("THE COAST HAS A SOUND.","SUNWARD / IN-CAR RADIO");var p=radioPanel.transform;Text(p,"Three frequencies. Take your favorite road with you.",64,194,1600,42,26,Muted);
  int count=r.Library?r.Library.stations.Length:0;stationCards=new UnityEngine.UI.Image[count];
  for(int i=0;i<count;i++){int index=i;var st=r.Library.stations[i];var b=Button(p,"",64+i*596,260,562,210,()=>r.SelectStation(index));stationCards[i]=b.GetComponent<UnityEngine.UI.Image>();Box(b.transform,"Station stripe",0,0,562,5,st.color);Label(b.transform,st.name.ToUpperInvariant(),25,23,340,st.color);Text(b.transform,st.frequency,24,58,310,67,52,Cream,FontStyles.Bold);Text(b.transform,st.tagline,26,135,510,34,23,Cream);Text(b.transform,st.tracks.Length+" TRACKS  /  TUNE IN",27,177,490,26,16,Muted,FontStyles.Bold);}
  var deck=Box(p,"Radio console",64,506,1106,442,Panel,true);Label(deck.transform,"YOUR SOUNDTRACK",29,26,690,Yellow);radioMenuState=Text(deck.transform,"",780,26,293,27,17,Muted,FontStyles.Bold,TextAlignmentOptions.TopRight);radioMenuStation=Text(deck.transform,"",30,80,1025,45,28,Teal,FontStyles.Bold);radioMenuTitle=Text(deck.transform,"",26,131,1045,82,60,Cream,FontStyles.Bold);radioArtist=Text(deck.transform,"",30,220,1010,37,25,Muted);Box(deck.transform,"Full timeline",30,291,1044,5,new Color(.24f,.30f,.29f));radioMenuProgress=Box(deck.transform,"Full progress",30,291,0,5,Teal);radioClock=Text(deck.transform,"",30,312,1040,30,18,Muted,FontStyles.Bold);Button(deck.transform,"NEXT TRACK  /  N",30,370,500,48,()=>r.NextTrack());radioPower=Button(deck.transform,"RADIO OFF  /  V",554,370,522,48,()=>r.Toggle()).GetComponentInChildren<TextMeshProUGUI>();
  var mix=Box(p,"Audio levels",1200,506,646,442,Panel,true);Label(mix.transform,"MAKE ROOM FOR THE MUSIC",28,26,590,Yellow);masterSlider=VolumeSlider(mix.transform,"MASTER",86,r.MasterVolume,r.SetMaster,out masterLabel);musicSlider=VolumeSlider(mix.transform,"RADIO",178,r.MusicVolume,r.SetMusic,out musicLabel);effectsSlider=VolumeSlider(mix.transform,"DRIVING & EFFECTS",270,r.EffectsVolume,r.SetEffects,out effectsLabel);radioMute=Button(mix.transform,"MUTE ALL  /  F8",28,370,590,48,()=>r.ToggleMute()).GetComponentInChildren<TextMeshProUGUI>();Text(p,"T / D-PAD RIGHT  station     N / D-PAD LEFT  next track     V  radio on/off     B / ESC  back to the road",64,998,1790,34,22,Muted);
 }
 UnityEngine.UI.Slider VolumeSlider(Transform p,string title,float y,float value,Action<float> change,out TextMeshProUGUI label){
  Label(p,title,29,y,450,Cream);label=Text(p,"",476,y,140,28,20,Muted,FontStyles.Bold,TextAlignmentOptions.TopRight);var root=Rect(p,title+" volume",30,y+30,582,38);var bg=Box(root,"Slider hit target",0,0,582,38,new Color(1,1,1,.001f));bg.raycastTarget=true;Box(root,"Track",0,16,582,6,new Color(.24f,.30f,.29f));var fillArea=Rect(root,"Fill area",0,16,582,6);var fill=Image(Fill(fillArea,"Level"),Yellow);var handleArea=Rect(root,"Handle area",12,7,558,24);var handle=Image(Fill(handleArea,"Handle"),Cream);handle.sprite=dotSprite;handle.rectTransform.sizeDelta=new Vector2(24,0);var slider=root.gameObject.AddComponent<UnityEngine.UI.Slider>();slider.fillRect=fill.rectTransform;slider.handleRect=handle.rectTransform;slider.targetGraphic=handle;slider.minValue=0;slider.maxValue=1;slider.SetValueWithoutNotify(value);slider.onValueChanged.AddListener(v=>change(v));return slider;
 }
 void RefreshRadio(){var r=S.Game.Radio;if(!r||!radioName)return;var st=r.Station;Color color=st!=null?st.color:Muted;string station=st!=null?st.name.ToUpperInvariant()+"  /  "+st.frequency:"SUNWARD RADIO";string title=r.On?(r.Track?.title??"Tuning in..."):"Just you and the road.";radioName.text=station;radioName.color=color;radioTitle.text=title;radioState.text=r.Status;radioAccent.color=color;radioProgress.color=color;radioProgress.rectTransform.sizeDelta=new Vector2(490*r.Progress,2);
  if(S.Menu!=FestivalMenu.Radio)return;radioMenuStation.text=station;radioMenuStation.color=color;radioMenuTitle.text=title;radioArtist.text=r.On?(r.Track?.artist??""):"Select a station to bring the music back.";radioMenuState.text=r.Status;radioMenuProgress.color=color;radioMenuProgress.rectTransform.sizeDelta=new Vector2(1044*r.Progress,5);radioClock.text=r.On?$"{(int)r.Position/60:00}:{(int)r.Position%60:00}  /  {(int)r.Duration/60:00}:{(int)r.Duration%60:00}":"";radioPower.text=r.On?"RADIO OFF  /  V":"RADIO ON  /  V";radioMute.text=r.Muted?"UNMUTE ALL  /  F8":"MUTE ALL  /  F8";
  for(int i=0;i<stationCards.Length;i++)stationCards[i].color=i==r.StationIndex?Color.Lerp(Panel,r.Library.stations[i].color,.20f):new Color(.10f,.15f,.18f);masterSlider.SetValueWithoutNotify(r.MasterVolume);musicSlider.SetValueWithoutNotify(r.MusicVolume);effectsSlider.SetValueWithoutNotify(r.EffectsVolume);masterLabel.text=Mathf.RoundToInt(r.MasterVolume*100)+"%";musicLabel.text=Mathf.RoundToInt(r.MusicVolume*100)+"%";effectsLabel.text=Mathf.RoundToInt(r.EffectsVolume*100)+"%";
 }

 void Reflow(){var bounds=((RectTransform)canvas.transform).rect;if(lastCanvasSize==bounds.size&&lastLayoutRace==S.RaceActive)return;lastCanvasSize=bounds.size;lastLayoutRace=S.RaceActive;menuStage.localScale=Vector3.one*Mathf.Min(bounds.width/1920f,bounds.height/1080f);bool narrow=bounds.width<1780,racing=S.RaceActive;((RectTransform)raceRoot.transform).anchoredPosition=new Vector2(-366,narrow?-180:-35);checkpointDistance.rectTransform.anchoredPosition=new Vector2(-310,narrow?-308:-170);((RectTransform)noticeRoot.transform).anchoredPosition=new Vector2(-330,narrow&&racing?-353:-204);}
 RectTransform Marker(Transform parent,float size,Color color,bool arrow){var r=Rect(parent,arrow?"Your position":"Next gate",0,0,size,size);r.pivot=new Vector2(.5f,.5f);var im=Image(r,color);if(arrow){im.sprite=ArrowSprite();}else im.sprite=ringSprite;return r;}
 void PlaceMarker(RectTransform r,Vector3 p,float size,bool rotate){var uv=MapUV(p);r.anchoredPosition=new Vector2(uv.x*size,-(1-uv.y)*size);if(rotate)r.localRotation=Quaternion.Euler(0,0,-S.Game.Player.transform.eulerAngles.y);}
 Vector2 MapUV(Vector3 p)=>new(Mathf.Clamp01((p.x-mapMin.x)/(mapMax.x-mapMin.x)),Mathf.Clamp01((p.z-mapMin.y)/(mapMax.y-mapMin.y)));
 void DrawLandmarks(Transform p,float size,float markerSize){for(int i=0;i<S.Game.World.Landmarks.Count;i++){var landmark=S.Game.World.Landmarks[i];var uv=MapUV(landmark.Position);var icon=Box(p,landmark.Name,uv.x*size-markerSize*.5f,(1-uv.y)*size-markerSize*.5f,markerSize,markerSize,landmark.Color);icon.sprite=dotSprite;}}
 void BuildMapTexture(){const int size=640;mapMin=new Vector2(float.MaxValue,float.MaxValue);mapMax=new Vector2(float.MinValue,float.MinValue);foreach(var road in S.Game.World.Roads)foreach(var p in road.Points){mapMin=Vector2.Min(mapMin,new Vector2(p.x,p.z));mapMax=Vector2.Max(mapMax,new Vector2(p.x,p.z));}Vector2 center=(mapMin+mapMax)*.5f;float extent=Mathf.Max(mapMax.x-mapMin.x,mapMax.y-mapMin.y)*.55f+90;mapMin=center-Vector2.one*extent;mapMax=center+Vector2.one*extent;mapTexture=new Texture2D(size,size,TextureFormat.RGBA32,false){name="Sunward discovery atlas",filterMode=FilterMode.Bilinear};var pixels=new Color32[size*size];
  for(int y=0;y<size;y++)for(int x=0;x<size;x++){float wx=Mathf.Lerp(mapMin.x,mapMax.x,x/(float)(size-1)),wz=Mathf.Lerp(mapMin.y,mapMax.y,y/(float)(size-1));float h=S.Game.World.GroundHeight(wx,wz);float shade=Mathf.Clamp01(h/90);Color c=h<0?new Color(.047f,.13f,.17f):Color.Lerp(new Color(.095f,.20f,.20f),new Color(.19f,.29f,.25f),shade);if(x%64==0||y%64==0)c=Color.Lerp(c,Cream,.035f);pixels[y*size+x]=c;}
  foreach(var road in S.Game.World.Roads){Color col=road.MapColor;for(int i=1;i<road.Points.Length;i++){Vector2 a=MapUV(road.Points[i-1])*(size-1),b=MapUV(road.Points[i])*(size-1);DrawLine(pixels,size,a,b,new Color(.025f,.075f,.09f),6);}}foreach(var road in S.Game.World.Roads){for(int i=1;i<road.Points.Length;i++){Vector2 a=MapUV(road.Points[i-1])*(size-1),b=MapUV(road.Points[i])*(size-1);DrawLine(pixels,size,a,b,Color.Lerp(road.MapColor,Cream,.55f),3);}}
  mapTexture.SetPixels32(pixels);mapTexture.Apply(false,true);
 }
 static void DrawLine(Color32[] pixels,int size,Vector2 a,Vector2 b,Color color,int radius){int steps=Mathf.CeilToInt(Vector2.Distance(a,b)*1.4f);for(int i=0;i<=steps;i++){Vector2 p=Vector2.Lerp(a,b,steps==0?0:i/(float)steps);int cx=Mathf.RoundToInt(p.x),cy=Mathf.RoundToInt(p.y);for(int y=-radius;y<=radius;y++)for(int x=-radius;x<=radius;x++){int px=cx+x,py=cy+y;if(px>=0&&py>=0&&px<size&&py<size&&x*x+y*y<=radius*radius)pixels[py*size+px]=color;}}}
 void MiniRoute(Transform p,RoadPath road,float x,float y,float w,float h,Color color){Vector2 min=new(float.MaxValue,float.MaxValue),max=new(float.MinValue,float.MinValue);foreach(var pos in road.Points){min=Vector2.Min(min,new Vector2(pos.x,pos.z));max=Vector2.Max(max,new Vector2(pos.x,pos.z));}float scale=Mathf.Min((w-20)/Mathf.Max(1,max.x-min.x),(h-20)/Mathf.Max(1,max.y-min.y));Vector2 offset=new Vector2(x+w*.5f,y+h*.5f)-(min+max)*.5f*scale;for(int i=1;i<road.Points.Length;i++){Vector2 a=new(road.Points[i-1].x,road.Points[i-1].z),b=new(road.Points[i].x,road.Points[i].z);a=a*scale+offset;b=b*scale+offset;var line=Box(p,"Road trace",a.x,y+h-(a.y-y),Vector2.Distance(a,b)+1,3,color);line.rectTransform.pivot=new Vector2(0,.5f);line.rectTransform.localRotation=Quaternion.Euler(0,0,Mathf.Atan2(b.y-a.y,b.x-a.x)*Mathf.Rad2Deg);}}
 Sprite Shape(bool ring,bool circle){const int n=64;var texture=new Texture2D(n,n,TextureFormat.RGBA32,false){name=ring?"Instrument ring":"Interface shape",filterMode=FilterMode.Bilinear};var pixels=new Color[n*n];for(int y=0;y<n;y++)for(int x=0;x<n;x++){float distance=Vector2.Distance(new Vector2(x+.5f,y+.5f),new Vector2(32,32));float alpha;if(ring)alpha=Mathf.Clamp01(32-distance)*Mathf.Clamp01(distance-27);else if(circle)alpha=Mathf.Clamp01(32-distance);else{Vector2 q=new Vector2(Mathf.Abs(x-31.5f),Mathf.Abs(y-31.5f))-Vector2.one*20;float d=new Vector2(Mathf.Max(0,q.x),Mathf.Max(0,q.y)).magnitude+Mathf.Min(Mathf.Max(q.x,q.y),0)-11;alpha=Mathf.Clamp01(-d);}pixels[y*n+x]=new Color(1,1,1,alpha);}texture.SetPixels(pixels);texture.Apply(false,true);return Sprite.Create(texture,new UnityEngine.Rect(0,0,n,n),new Vector2(.5f,.5f),100,0,SpriteMeshType.FullRect,new Vector4(16,16,16,16));}
 Sprite arrowSprite;Sprite ArrowSprite(){if(arrowSprite)return arrowSprite;const int n=32;var texture=new Texture2D(n,n,TextureFormat.RGBA32,false){name="Player compass arrow",filterMode=FilterMode.Bilinear};var pixels=new Color[n*n];for(int y=0;y<n;y++)for(int x=0;x<n;x++){float py=y/(float)n,dx=Mathf.Abs((x+.5f)/n-.5f);bool on=dx<(.5f*(1-py))&&py>.15f+dx*.35f;pixels[y*n+x]=new Color(1,1,1,on?1:0);}texture.SetPixels(pixels);texture.Apply(false,true);arrowSprite=Sprite.Create(texture,new UnityEngine.Rect(0,0,n,n),new Vector2(.5f,.5f));return arrowSprite;}
 void OnDestroy(){if(ownsFont&&font)Destroy(font);if(mapTexture)Destroy(mapTexture);DestroySprite(panelSprite);DestroySprite(ringSprite);DestroySprite(dotSprite);DestroySprite(arrowSprite);}
 static void DestroySprite(Sprite s){if(!s)return;if(s.texture)Destroy(s.texture);Destroy(s);}
}
}
