using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.LowLevel;

namespace Sunward {
public sealed class PhotoVerification:MonoBehaviour {
 public string destination;readonly List<string> checks=new(),errors=new(),photos=new();SunwardGame game;PhotoMode photo;float blurDifference,monoChroma;int width,height;bool finished;
 [Serializable] sealed class Evidence {public bool passed;public string[] checks,errors,photos;public int width,height;public float blurDifference,monoChroma,averageFps;public long memoryBytes;}
 [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)] static void Begin(){var args=Environment.GetCommandLineArgs();int i=Array.IndexOf(args,"-sunward-photo-verify");if(i<0||i+1>=args.Length)return;var test=new GameObject("Photo verification").AddComponent<PhotoVerification>();DontDestroyOnLoad(test);test.destination=Path.GetFullPath(args[i+1]);}
 void Awake()=>Application.logMessageReceived+=Log;
 void Log(string message,string stack,LogType type){if(type==LogType.Error||type==LogType.Exception||type==LogType.Assert)errors.Add(message+"\n"+stack);}
 void Check(bool ok,string label){if(ok)checks.Add(label);else errors.Add(label);}
 IEnumerator KeyPress(Key key){var keyboard=Keyboard.current??InputSystem.AddDevice<Keyboard>();InputSystem.QueueStateEvent(keyboard,new KeyboardState(key));yield return null;yield return null;InputSystem.QueueStateEvent(keyboard,new KeyboardState());yield return null;}
 IEnumerator WaitCapture(){float until=Time.realtimeSinceStartup+20;while(photo.Busy&&Time.realtimeSinceStartup<until)yield return null;Check(!photo.Busy,"Capture completes without blocking simulation controls");}
 IEnumerator Save(string name){yield return null;yield return null;photo.Capture();yield return WaitCapture();if(File.Exists(photo.LastPhoto)){string path=Path.Combine(destination,name+".png");File.Copy(photo.LastPhoto,path,true);photos.Add(path);}else Check(false,"Photo saved: "+name);}
 Texture2D Load(string name){var image=new Texture2D(2,2,TextureFormat.RGB24,false);if(!image.LoadImage(File.ReadAllBytes(Path.Combine(destination,name+".png"))))Check(false,"PNG decoding: "+name);return image;}
 IEnumerator Screen(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(destination,name+".png"));yield return new WaitForSecondsRealtime(.25f);}
 IEnumerator Start(){
  Directory.CreateDirectory(destination);float until=Time.realtimeSinceStartup+40;while((!SunwardGame.Instance||!SunwardGame.Instance.Ready)&&Time.realtimeSinceStartup<until)yield return null;game=SunwardGame.Instance;if(!game||!game.Ready){Check(false,"Startup timeout");Finish(0);yield break;}photo=game.Photo;photo.DirectoryPath=Path.Combine(destination,"captures");yield return new WaitForSecondsRealtime(.3f);
  var cam=game.ViewCamera;var oldPos=cam.transform.position;var oldRot=cam.transform.rotation;float oldFov=cam.fieldOfView,oldNear=cam.nearClipPlane;bool oldInput=game.Player.InputEnabled;
  photo.Enter();Check(photo.Active&&game.Session.Menu==FestivalMenu.Photo&&Time.timeScale==0,"Photo mode pauses the world");photo.Exit();Check(Vector3.Distance(cam.transform.position,oldPos)<.001f&&Quaternion.Angle(cam.transform.rotation,oldRot)<.01f&&Mathf.Abs(cam.fieldOfView-oldFov)<.01f&&cam.nearClipPlane==oldNear,"Exact camera pose, FOV and clipping restored");Check(Time.timeScale==1&&game.Player.enabled&&game.CameraRig.enabled&&game.Player.InputEnabled==oldInput,"Driving components and input restored");
  yield return KeyPress(Key.P);Check(photo.Active,"P enters photo mode");Check(!game.Player.enabled&&!game.Player.InputEnabled&&!game.CameraRig.enabled,"Driving input and camera cannot fight photo controls");
  var body=game.Player.Body;var pos=body.position;var velocity=body.linearVelocity;var travellers=game.Traffic.GetComponentsInChildren<Rigidbody>();var locations=travellers.Select(t=>t.position).ToArray();yield return new WaitForSecondsRealtime(.6f);Check(body.position==pos&&body.linearVelocity==velocity,"Player pose and velocity remain frozen");Check(travellers.Length>0&&travellers.Select((t,i)=>Vector3.Distance(t.position,locations[i])<.001f).All(x=>x),"Traffic stays frozen");
  Vector3 target=game.Player.transform.position+Vector3.up*.85f;oldPos=cam.transform.position;photo.MoveCamera(Vector3.right,.15f);Check(Vector3.Distance(cam.transform.position,oldPos)>.5f&&Vector3.Dot(cam.transform.forward,(target-cam.transform.position).normalized)>.999f,"Orbit movement keeps the car centered");float distance=Vector3.Distance(cam.transform.position,target);photo.RotateCamera(new Vector2(23,5));Check(Mathf.Abs(Vector3.Distance(cam.transform.position,target)-distance)<.01f,"Orbit look preserves camera distance");
  yield return KeyPress(Key.O);Check(!photo.Orbit,"O switches to free flight");oldPos=cam.transform.position;oldRot=cam.transform.rotation;photo.RotateCamera(new Vector2(15,5));Check(cam.transform.position==oldPos&&Quaternion.Angle(cam.transform.rotation,oldRot)>10,"Free look rotates without moving the camera");oldPos=cam.transform.position;yield return KeyPress(Key.W);Check(Vector3.Distance(cam.transform.position,oldPos)>.001f,"W moves the free camera");oldPos=cam.transform.position;yield return KeyPress(Key.E);Check(cam.transform.position.y>oldPos.y&&game.Session.Menu==FestivalMenu.Photo,"E raises the camera without opening events");
  yield return KeyPress(Key.G);Check(photo.Grid&&game.Session.Menu==FestivalMenu.Photo,"G toggles composition grid without opening garage");yield return KeyPress(Key.H);Check(!photo.InterfaceVisible&&!game.Session.HUD.GetComponentsInChildren<UnityEngine.UI.Button>().Any(b=>b.name=="TAKE PHOTO / SPACE"),"H hides photo controls");yield return KeyPress(Key.H);Check(photo.InterfaceVisible,"H restores photo controls");
  photo.MoveCamera(Vector3.up,100);Check(Vector3.Distance(cam.transform.position,target)<=200.1f,"Free camera remains in the supported world radius");yield return KeyPress(Key.R);Check(photo.Orbit&&photo.Roll==0&&photo.Lens==50,"R resets the composition");
  var slider=game.Session.HUD.GetComponentsInChildren<UnityEngine.UI.Slider>().First(s=>s.name=="LENS photo slider");slider.value=70;Check(photo.Lens==70&&cam.fieldOfView<21,"Lens slider controls perspective");photo.SetRoll(14);Check(Mathf.Abs(Mathf.DeltaAngle(0,cam.transform.eulerAngles.z)-14)<.1f,"Camera roll adjusts the horizon");photo.SetFocus(3);photo.SetAperture(1.4f);photo.SetExposure(.7f);Check(photo.Focus==3&&photo.Aperture==1.4f&&photo.Exposure==.7f,"Focus, aperture and exposure controls work");photo.SetExposure(0);photo.SetAperture(2);photo.ResetCamera();yield return KeyPress(Key.F);Check(Mathf.Abs(photo.Focus-Vector3.Distance(cam.transform.position,target))<.01f,"F focuses on the car");
  yield return Screen("photo-mode");var capture=game.Session.HUD.GetComponentsInChildren<UnityEngine.UI.Button>().First(b=>b.name=="TAKE PHOTO / SPACE");capture.onClick.Invoke();photo.Capture();Check(photo.Busy,"Capture button begins a single guarded export");yield return WaitCapture();Check(File.Exists(photo.LastPhoto),"4K PNG written");if(!File.Exists(photo.LastPhoto)){Finish(0);yield break;}File.Copy(photo.LastPhoto,Path.Combine(destination,"sunward-4k.png"),true);photos.Add(Path.Combine(destination,"sunward-4k.png"));Check(Directory.GetFiles(photo.DirectoryPath,"*.png").Length==1,"Repeated shutter presses cannot overlap captures");var original=Load("sunward-4k");width=original.width;height=original.height;Check(Mathf.Max(width,height)==3840&&Mathf.Abs((float)width/height-cam.aspect)<.002f,"4K export preserves the view aspect ratio");Destroy(original);
  photo.CycleResolution();photo.SetLens(60);photo.SetFocus(.3f);photo.SetAperture(1);yield return Save("blur");photo.ToggleBlur();yield return Save("sharp");var blurred=Load("blur");var sharp=Load("sharp");Check(Mathf.Max(sharp.width,sharp.height)==1920,"HD export resolution works");double diff=0;int count=0;for(int y=10;y<sharp.height;y+=12)for(int x=10;x<sharp.width;x+=12){var a=blurred.GetPixel(x,y);var b=sharp.GetPixel(x,y);diff+=Math.Abs(a.r-b.r)+Math.Abs(a.g-b.g)+Math.Abs(a.b-b.b);count++;}blurDifference=(float)(diff/count/3*255);Check(blurDifference>.5f,"Depth of field produces a visible difference in native exports");Destroy(blurred);Destroy(sharp);
  for(int i=0;i<3;i++)photo.CycleLook();Check(photo.Look==3,"Four distinct color presets available");yield return Save("mono");var mono=Load("mono");double chroma=0;count=0;for(int y=10;y<mono.height;y+=16)for(int x=10;x<mono.width;x+=16){var c=mono.GetPixel(x,y);chroma+=Math.Abs(c.r-c.g)+Math.Abs(c.g-c.b);count++;}monoChroma=(float)(chroma/count*255);Check(monoChroma<3,"Monochrome preset renders into saved photos");Destroy(mono);photo.CycleLook();photo.ToggleBlur();photo.SetAperture(2);photo.ResetCamera();
  string directory=photo.DirectoryPath;string blocked=Path.Combine(destination,"occupied-file");File.WriteAllText(blocked,"capture failure test");photo.DirectoryPath=blocked;photo.Capture();yield return WaitCapture();Check(photo.Message.StartsWith("PHOTO COULD NOT BE SAVED")&&photo.Active&&cam.targetTexture==null&&game.Session.HUD.GetComponent<UnityEngine.Canvas>().enabled,"Write failure leaves the camera and UI usable");photo.DirectoryPath=directory;File.Delete(blocked);yield return KeyPress(Key.Space);yield return WaitCapture();Check(photo.Message.StartsWith("SAVED")&&File.Exists(photo.LastPhoto),"Space captures again after a write failure");Check(!Directory.GetFiles(directory,"*.tmp").Any(),"No unfinished temporary photos remain");
  Check(FindObjectsByType<AudioListener>().Length==1&&game.Radio.Playing,"Radio continues with one audio listener");yield return KeyPress(Key.Escape);Check(!photo.Active&&game.Session.Menu==FestivalMenu.None&&Time.timeScale==1,"Escape returns to driving");
  foreach(var menu in new[]{FestivalMenu.Pause,FestivalMenu.Radio,FestivalMenu.Garage}){game.Session.ShowMenu(menu);if(menu==FestivalMenu.Garage)game.Session.Preview((game.CurrentCarIndex+1)%CarSpec.All.Length);int car=game.CurrentCarIndex;photo.Enter();photo.Exit();Check(game.Session.Menu==menu&&Time.timeScale==0&&game.CurrentCarIndex==car,"Photo mode returns to "+menu+" without losing its state");game.Session.CloseMenu();}
  game.Session.StartEvent(0);yield return new WaitForSecondsRealtime(.3f);photo.Enter();float countdown=game.Session.Countdown;yield return new WaitForSecondsRealtime(.4f);Check(game.Session.Countdown==countdown,"Race countdown stays paused");photo.Exit();yield return new WaitForSecondsRealtime(3.2f);Check(game.Session.State==FestivalRace.Racing,"Countdown resumes into a race");body.linearVelocity=game.Player.transform.forward*16;photo.Enter();float raceTime=game.Session.RaceTime;pos=body.position;velocity=body.linearVelocity;var progress=(float[])game.Traffic.RaceDistances.Clone();yield return new WaitForSecondsRealtime(.5f);Check(game.Session.RaceTime==raceTime&&game.Traffic.RaceDistances.SequenceEqual(progress)&&body.position==pos&&body.linearVelocity==velocity,"Moving car, rivals and race timer freeze together");Check(!game.Session.PhotoNavigation.activeSelf,"Navigation ribbon is hidden for photography");photo.Exit();Check(game.Session.PhotoNavigation.activeSelf,"Race navigation restores after photography");yield return new WaitForSecondsRealtime(.3f);Check(game.Session.RaceTime>raceTime&&Vector3.Distance(body.position,pos)>.1f,"Race timer and moving car resume");game.Session.AbandonEvent();game.Session.ReturnToFestival();
  photo.Enter();photo.CycleResolution();photo.ResetCamera();yield return new WaitForSecondsRealtime(.15f);yield return Screen("photo-mode-final");float start=Time.realtimeSinceStartup;for(int f=0;f<90;f++)yield return null;float fps=90/(Time.realtimeSinceStartup-start);Finish(fps);
 }
 void Finish(float fps){if(finished)return;finished=true;var e=new Evidence{passed=errors.Count==0,checks=checks.ToArray(),errors=errors.ToArray(),photos=photos.ToArray(),width=width,height=height,blurDifference=blurDifference,monoChroma=monoChroma,averageFps=fps,memoryBytes=UnityEngine.Profiling.Profiler.GetTotalAllocatedMemoryLong()};File.WriteAllText(Path.Combine(destination,"photo-validation.json"),JsonUtility.ToJson(e,true));
#if UNITY_EDITOR
  Debug.Log("SUNWARD_PHOTO_VALIDATION "+e.passed);Destroy(gameObject);
#else
  Application.Quit(e.passed?0:1);
#endif
 }
 void OnDestroy(){Application.logMessageReceived-=Log;}
}
}
