using System.Collections.Generic;
using UnityEngine;

namespace Sunward {
public sealed class TrafficSystem:MonoBehaviour {
 sealed class Driver {public RoadPath Road;public Transform Root;public VehicleVisual Visual;public Rigidbody Body;public float Distance,Speed,Cruise,Lane;public int Direction;public bool Opponent;}
 readonly List<Driver> drivers=new(); readonly List<Driver> rivals=new();
 public float[] RaceDistances=new float[3]; public bool Racing; public int TrafficCount=>drivers.Count;
 WorldBuilder world;ArcadeCar player;
 public void Initialize(WorldBuilder w,ArcadeCar p){world=w;player=p;var random=new System.Random(8427);for(int r=0;r<w.Roads.Count;r++){var path=w.Roads[r];int count=Mathf.Clamp(Mathf.RoundToInt(path.Length/170),12,28);for(int i=0;i<count;i++){float d=(i+.37f)*path.Length/count; if(Vector3.Distance(path.Position(d),w.SpawnPosition)<50)continue;drivers.Add(Create(path,d,i%2==0?1:-1,13+(float)random.NextDouble()*9,false,i));}}}
 Driver Create(RoadPath road,float distance,int direction,float speed,bool race,int seed){var root=new GameObject(race?"Festival rival":"Road traveller");root.transform.SetParent(transform);var spec=CarSpec.All[seed%CarSpec.All.Length];Color color=race?new[]{new Color(.11f,.64f,.63f),new Color(.85f,.68f,.2f),new Color(.50f,.40f,.75f)}[seed%3]:Color.HSVToRGB((seed*.173f)%1,.22f+(seed%3)*.17f,.42f+(seed%4)*.13f);var visual=VehicleArt.Build(root.transform,spec,color,!race);var body=root.AddComponent<Rigidbody>();body.isKinematic=true;body.interpolation=RigidbodyInterpolation.Interpolate;var box=root.AddComponent<BoxCollider>();box.center=new Vector3(0,.78f,0);box.size=new Vector3(1.9f,1.1f,4.1f);var dr=new Driver{Road=road,Root=root.transform,Visual=visual,Body=body,Distance=distance,Direction=direction,Cruise=speed,Speed=race?0:speed,Lane=direction*(race?((seed%2==0)?2.8f:-.6f):3f),Opponent=race};Place(dr,true);return dr;}
 void Place(Driver d,bool teleport=false){d.Road.Sample(d.Distance,out var pos,out var tangent);Vector3 right=Vector3.Cross(Vector3.up,tangent).normalized;pos+=right*d.Lane+Vector3.up*.045f;var rotation=Quaternion.LookRotation(tangent*d.Direction,Vector3.up);if(teleport){d.Body.position=pos;d.Body.rotation=rotation;}else{d.Body.MovePosition(pos);d.Body.MoveRotation(Quaternion.Slerp(d.Body.rotation,rotation,Time.fixedDeltaTime*9));}d.Visual.Animate(d.Speed,0,0,false);}
 public void StartRace(RoadPath route,int laps){StopRace();Racing=true;for(int i=0;i<3;i++){var d=Create(route,6+i*8,1,30+i*2.3f,true,i);rivals.Add(d);RaceDistances[i]=d.Distance;}}
 public void StopRace(){foreach(var d in rivals)if(d.Root)Destroy(d.Root.gameObject);rivals.Clear();Racing=false;for(int i=0;i<RaceDistances.Length;i++)RaceDistances[i]=0;}
 void FixedUpdate(){float dt=Time.fixedDeltaTime;for(int i=0;i<drivers.Count;i++){var d=drivers[i];if(!d.Root)continue;float target=d.Cruise;var tangent=d.Road.Rotation(d.Distance)*Vector3.forward*d.Direction;Vector3 toPlayer=player.transform.position-d.Root.position;float along=Vector3.Dot(toPlayer,tangent);if(along>0&&along<30&&Mathf.Abs(Vector3.Dot(toPlayer,Vector3.Cross(Vector3.up,tangent)))<2.4f){target=Mathf.Min(target,Mathf.Max(0,(along-7)*.9f+Vector3.Dot(player.Body.linearVelocity,tangent)*.5f));}d.Speed=Mathf.MoveTowards(d.Speed,target,dt*(target<d.Speed?9:2.4f));d.Distance+=d.Speed*dt*d.Direction;Place(d);}
  for(int i=0;i<rivals.Count;i++){var d=rivals[i];Vector3 f0=d.Road.Rotation(d.Distance)*Vector3.forward,f1=d.Road.Rotation(d.Distance+45)*Vector3.forward;float bend=Vector3.Angle(f0,f1);float target=d.Cruise*Mathf.Lerp(1,.54f,Mathf.InverseLerp(8,65,bend));float playerDistance=d.Road.ClosestDistance(player.transform.position);float lead=d.Distance-playerDistance;if(lead>180)target*=.87f;else if(lead < -220)target*=1.08f;d.Speed=Mathf.MoveTowards(d.Speed,target,dt*7);d.Distance+=d.Speed*dt;d.Lane=Mathf.MoveTowards(d.Lane,2.25f+Mathf.Sin(d.Distance*.0035f+i*2.2f)*1.4f,dt*.6f);Place(d);RaceDistances[i]=d.Distance;}
 }
}
}
