using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering;

namespace Sunward {
internal sealed class WorldArt {
 sealed class Batch {public List<Vector3> V=new();public List<Vector3>N=new();public List<Vector2> U=new();public Dictionary<int,List<int>> T=new();}
 readonly Dictionary<Vector2Int,Batch> batches=new(); readonly List<Material> materials=new(); readonly Transform parent;
 public WorldArt(Transform t){parent=t;}
 public int Mat(string name,Color c,float smooth=.12f,float metal=0,Color? emission=null){var m=new Material(Shader.Find("Universal Render Pipeline/Lit")){name=name,color=c};m.SetFloat("_Smoothness",smooth);m.SetFloat("_Metallic",metal);if(emission.HasValue){m.EnableKeyword("_EMISSION");m.SetColor("_EmissionColor",emission.Value);}materials.Add(m);return materials.Count-1;}
 public Material Material(int i)=>materials[i];
 Batch At(Vector3 p){var k=new Vector2Int(Mathf.FloorToInt(p.x/240),Mathf.FloorToInt(p.z/240));if(!batches.TryGetValue(k,out var b))batches.Add(k,b=new Batch());return b;}
 public void Tri(int m,Vector3 a,Vector3 b,Vector3 c,Vector2 u=default,Vector2 v=default,Vector2 w=default){var d=At((a+b+c)/3);int n=d.V.Count;d.V.Add(a);d.V.Add(b);d.V.Add(c);Vector3 normal=Vector3.Cross(b-a,c-a).normalized;d.N.Add(normal);d.N.Add(normal);d.N.Add(normal);d.U.Add(u);d.U.Add(v);d.U.Add(w);if(!d.T.TryGetValue(m,out var t))d.T.Add(m,t=new List<int>());t.Add(n);t.Add(n+1);t.Add(n+2);}
 public void Quad(int m,Vector3 a,Vector3 b,Vector3 c,Vector3 d){Tri(m,a,b,c,new(0,0),new(0,1),new(1,1));Tri(m,a,c,d,new(0,0),new(1,1),new(1,0));}
 public void Surface(int m,Vector3 a,Vector3 b,Vector3 c,Vector3 d,float scale=.25f){Vector2 UV(Vector3 p)=>new Vector2(p.x,p.z)*scale;Tri(m,a,b,c,UV(a),UV(b),UV(c));Tri(m,a,c,d,UV(a),UV(c),UV(d));}
 public void Box(int m,Vector3 p,Vector3 size,Quaternion q){Vector3 P(float x,float y,float z)=>p+q*Vector3.Scale(new Vector3(x,y,z),size*.5f);Quad(m,P(-1,-1,-1),P(-1,1,-1),P(1,1,-1),P(1,-1,-1));Quad(m,P(1,-1,1),P(1,1,1),P(-1,1,1),P(-1,-1,1));Quad(m,P(-1,-1,1),P(-1,1,1),P(-1,1,-1),P(-1,-1,-1));Quad(m,P(1,-1,-1),P(1,1,-1),P(1,1,1),P(1,-1,1));Quad(m,P(-1,1,-1),P(-1,1,1),P(1,1,1),P(1,1,-1));Quad(m,P(-1,-1,1),P(-1,-1,-1),P(1,-1,-1),P(1,-1,1));}
 public void Beam(int m,Vector3 a,Vector3 b,float width,float depth=0){Box(m,(a+b)*.5f,new Vector3(width,width>0&&depth<=0?width:depth,Vector3.Distance(a,b)),Quaternion.LookRotation(b-a));}
 public void Cylinder(int m,Vector3 a,Vector3 b,float ra,float rb,int sides=8){Quaternion q=Quaternion.FromToRotation(Vector3.up,(b-a).normalized);for(int i=0;i<sides;i++){float t=i*2*Mathf.PI/sides,u=(i+1)*2*Mathf.PI/sides;Vector3 x=q*new Vector3(Mathf.Cos(t),0,Mathf.Sin(t)),y=q*new Vector3(Mathf.Cos(u),0,Mathf.Sin(u));Quad(m,a+x*ra,b+x*rb,b+y*rb,a+y*ra);Tri(m,b,b+y*rb,b+x*rb);Tri(m,a,a+x*ra,a+y*ra);}}
 public void Rock(int m,Vector3 p,Vector3 size,float seed,int rings=3,int sides=7){Vector3 Point(int r,int s){float lat=(r/(float)rings-.5f)*Mathf.PI,lon=s*2*Mathf.PI/sides;float noise=.87f+.23f*Mathf.PerlinNoise(seed+s*.61f,r*.77f);return p+Vector3.Scale(new Vector3(Mathf.Cos(lat)*Mathf.Cos(lon),Mathf.Sin(lat),Mathf.Cos(lat)*Mathf.Sin(lon)),size)*noise;}for(int r=0;r<rings;r++)for(int i=0;i<sides;i++)Quad(m,Point(r,i),Point(r+1,i),Point(r+1,(i+1)%sides),Point(r,(i+1)%sides));}
 public void Ring(int m,Vector3 p,Quaternion rotation,float radius,float tube,int count=40,int sides=6){Vector3 P(int i,int j){float a=i*2*Mathf.PI/count,b=j*2*Mathf.PI/sides;return p+rotation*new Vector3((radius+Mathf.Cos(b)*tube)*Mathf.Cos(a),(radius+Mathf.Cos(b)*tube)*Mathf.Sin(a),Mathf.Sin(b)*tube);}for(int i=0;i<count;i++)for(int j=0;j<sides;j++)Quad(m,P(i,j),P(i+1,j),P(i+1,j+1),P(i,j+1));}
 public void Arch(int m,Vector3 p,Quaternion q,float width,float height,float thick,float depth){float r=width*.5f;Vector3 P(float x,float y,float z)=>p+q*new Vector3(x,y,z);Box(m,P(-r-thick*.5f,(height-r)*.5f,0),new(thick,height-r,depth),q);Box(m,P(r+thick*.5f,(height-r)*.5f,0),new(thick,height-r,depth),q);for(int i=0;i<14;i++){float a=i*Mathf.PI/14,b=(i+1)*Mathf.PI/14;for(int side=-1;side<=1;side+=2){Vector3 A=P(Mathf.Cos(a)*r,height-r+Mathf.Sin(a)*r,side*depth*.5f),B=P(Mathf.Cos(b)*r,height-r+Mathf.Sin(b)*r,side*depth*.5f),C=P(Mathf.Cos(b)*(r+thick),height-r+Mathf.Sin(b)*(r+thick),side*depth*.5f),D=P(Mathf.Cos(a)*(r+thick),height-r+Mathf.Sin(a)*(r+thick),side*depth*.5f);if(side<0)Quad(m,A,B,C,D);else Quad(m,D,C,B,A);}Quad(m,P(Mathf.Cos(a)*r,height-r+Mathf.Sin(a)*r,-depth*.5f),P(Mathf.Cos(a)*r,height-r+Mathf.Sin(a)*r,depth*.5f),P(Mathf.Cos(b)*r,height-r+Mathf.Sin(b)*r,depth*.5f),P(Mathf.Cos(b)*r,height-r+Mathf.Sin(b)*r,-depth*.5f));}}
 public void Flush(){foreach(var pair in batches){var b=pair.Value;var go=new GameObject("Landscape sector "+pair.Key.x+" · "+pair.Key.y);go.transform.SetParent(parent,false);go.isStatic=true;var mesh=new Mesh{name=go.name,indexFormat=b.V.Count>65500?IndexFormat.UInt32:IndexFormat.UInt16};mesh.SetVertices(b.V);mesh.SetNormals(b.N);mesh.SetUVs(0,b.U);mesh.subMeshCount=b.T.Count;var mats=new Material[b.T.Count];int i=0;foreach(var sub in b.T){mesh.SetTriangles(sub.Value,i);mats[i++]=materials[sub.Key];}mesh.RecalculateBounds();go.AddComponent<MeshFilter>().sharedMesh=mesh;var r=go.AddComponent<MeshRenderer>();r.sharedMaterials=mats;r.shadowCastingMode=ShadowCastingMode.On;}batches.Clear();}
}
}
